### PR TITLE
Remove web-app related files from hardware repo

### LINKED ISSUE #1: Clear up web app codes
**User story**
The roadmap of this repo is to host code that are only needed to run on onboard hardware (R-Pi). The web app code should be removed from the repo.

**Acceptance criteria**
- The irrelevant code which belongs to [the other repo](https://github.com/mercury-telemetry/mercury-telemetry) is deleted from this repo.
- Tests and checks still pass.
- Travis credentials for automatic Docker deployment are updated.

**Definition of Done**
The change is completed, tested and merged.

### PR DESCRIPTION
**Pull request by ab7289**
## Description
This PR removes all of the webapp-related files from the hardware repo.

This closes #1 .

## Types of Changes
_Put an `x` in the boxes that apply_

- [ ] Feature (non-breaking change which adds functionality)
- [ ] Bug Fix (non-breaking change that fixes an issue)
- [x] Breaking Change (feature/fix that causes existing features to not work as expected)
- [ ] Documentation

## Checklist

- [x] I have read the [contribute]contributing<link> doc
- [x] Classes, scripts, and environment variables follow existing naming convention
- [x] Lint and Unit tests pass locally
- [x] New features on hardware have been tested on a local Raspberry Pi
- [x] Mention new programs/binaries if any must be installed along with this change
- [x] Mention new environment variables if any have been added to hardware/env file
- [x] Please make sure test coverage does not drop. If it does, please explain the reasons.
- [x] Any new required python modules are added to the requirements.txt

### CODE REVIEW

**Comment by ab7289** [comment]
I noticed that it's not running any status checks, maintainers should probably enable branch protection on master. As it currently stands anyone with write access can merge whatever they want into master.

**Comment by jackxujh** [comment]
@ab7289 this is a good point. we should enforce the requirement. @MichaelLally has the necessary admin access to set this rule. Hopefully we will hear back from him when he sees this message.

**Comment by jackxujh** [comment]
@ab7289 thanks for removing the web app files! As part of this removal of web app files, could you also remove the docs that are no longer relevant? They are still in the repo: https://github.com/ab7289/mercury-hardware/tree/master/docs

**Comment by ab7289** [comment]
Hey @jackxujh, thanks for the suggestion. I have updated the PR to remove the docs.

**Review by jackxujh — APPROVED** [review]
LGTM

**Pull request merged**
